# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/ollama/ollama
%global goipath         github.com/ollama/ollama
Version:                0.4.1-rc0

%gometa -L -f

%global common_description %{expand:
Get up and running with Llama 3.2, Mistral, Gemma 2, and other large language
models.}

%global golicenses      LICENSE
%global godocs          docs examples CONTRIBUTING.md README.md SECURITY.md\\\
                        app/README.md integration/README.md llama/README.md\\\
                        llama/runner/README.md macapp/README.md

source0:	ollama.service
Name:           ollama
Release:        %autorelease
Summary:        Get up and running with Llama 3.2, Mistral, Gemma 2, and other large language models

License:        Apache-2.0 AND MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/ollama %{goipath}
for cmd in app llama/runner; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
sudo useradd -r -s /bin/false -U -m -d /usr/share/ollama ollama
sudo usermod -a -G ollama $(whoami)
install -D -p -m 0644 %{SOURCE0} %{buildroot}%_unitdir/ollama.service

%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs examples CONTRIBUTING.md README.md SECURITY.md app/README.md
%doc integration/README.md llama/README.md llama/runner/README.md
%doc macapp/README.md
%{_bindir}/ollama
%endif

%gopkgfiles

%changelog
%autochangelog
